//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong_CT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DatPhong_CT()
        {
            this.tb_DatPhong_SanPham = new HashSet<tb_DatPhong_SanPham>();
        }
    
        public int IDDPCT { get; set; }
        public int IDDP { get; set; }
        public int IDPHONG { get; set; }
        public Nullable<int> SONGAYO { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual tb_DatPhong tb_DatPhong { get; set; }
        public virtual tb_Phong tb_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DatPhong_SanPham> tb_DatPhong_SanPham { get; set; }
    }
}
