//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong_SanPham
    {
        public int IDDPSP { get; set; }
        public Nullable<int> IDDPCT { get; set; }
        public int IDDP { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public Nullable<int> IDSP { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual tb_DatPhong tb_DatPhong { get; set; }
        public virtual tb_DatPhong_CT tb_DatPhong_CT { get; set; }
        public virtual tb_Phong tb_Phong { get; set; }
        public virtual tb_SanPham tb_SanPham { get; set; }
    }
}
