//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Param
    {
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public string TENCTY { get; set; }
        public string TENDVI { get; set; }
    }
}
