//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SYS_USER()
        {
            this.tb_DatPhong = new HashSet<tb_DatPhong>();
        }
    
        public int IDUSER { get; set; }
        public string FULLNAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWD { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public Nullable<System.DateTime> LAST_PWD_CHANGED { get; set; }
        public Nullable<bool> ISGROUP { get; set; }
        public Nullable<bool> DISABLED { get; set; }
    
        public virtual tb_CongTy tb_CongTy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DatPhong> tb_DatPhong { get; set; }
        public virtual tb_DonVi tb_DonVi { get; set; }
    }
}
